### ISSUE TITLE
An issue with highlight relevance

### ISSUE THREAD

**Issue by qexat** [mcb-dev/mCodingBot#116]
# An issue with highlight relevance

## Glossary

- **notification**: private message from the bot about the highlighted word.
- **TM**: triggering message, i.e. that contains an highlighted word.

## Synopsis

Let's say user A has `cat` in their highlighted words list.

If user B sends a message containing `cat`, user A will receive a notification about the TM.

However, if user B edits their message, it could happen not to contain the word anymore, making the notification irrelevant. This also means that the user A has access to the previous version of the message<sup>[[1]](#note-1)</sup>, which can have serious implications, that will be discussed further.

## Concerns

If `cat` is a pretty innocent substantive, an edge case subsists where the user B sends a rule-breaking TM. The message would have been deleted, but the user A will still be exposed to its contents through the notification.

For instance, the current rules prohibit hate speech<sup>[[2]](#note-2)</sup>. This means that one having a highlighted list is potentially exposing themselves to content they might did not want in the first place.

### TM tracking

TMs could be tracked for a given period of time -- if they get deleted, or edited, the bot can behave accordingly, removing the notification if needed.

One limitation of this proposal I can think of is that the ping of this notification is likely to stay (ghost ping).

An alternative could be that instead of deleting the notification, it would edit into saying something like: "This message has been edited/deleted".

## To go further

While writing this, other ideas of features emerge in my mind. This is the part where I list them.

### Word matching rather than character sequence

Currently, if one have `java` as a highlighted word, a message containing "javascript" is a TM.

It should preferably use pattern matching rather than a simple `word in message`<sup>[[3]](#note-3)</sup>.

### Channel-dependent highlights

I think it would be a very nice feature if we could add/remove specific channels for a given highlight -- although, the `highlight create` command should by default set up the highlight for every channel.

### Allow close-enough to trigger

User B could mistype a word, but user A would still want to get a notification for it.

This idea is kind of mutually exclusive with [this one](#word-matching-rather-than-character-sequence), because I am not sure how to mix pattern matching and levenshtein distance thresholding.

### Inhibitors

Inhibitors would be words that prevent a message from being TM even if they contained a highlight.

For example, if you have `rust` as a highlight and `javascript` has an inhibitor:

- "I like Rust" => TM
- "I like Rust and JavaScript" => not TM
- "I like JavaScript" => not TM

To go further, make inhibitors highlight-dependent -- one inhibitor would have an effect on a specific highlight but not on any other.

### Highlight temporary deactivation

One could want not to get notifications for a word for a certain time frame.
This idea is at the very bottom because it might have a real-world purpose.

### Note 1

That also implies that the user A would have access to contents that the user B deliberately decided to modify. Does this have legal implications? <sup>[[↑]](https://github.com/mcb-dev/mCodingBot/issues/116#:~:text=This%20also%20means%20that%20the%20user%20A%20has%20access%20to%20the%20previous%20version%20of%20the%20message)</sup>

### Note 2

Rule 9 links the Discord guidelines: https://discord.com/guidelines. <sup>[[↑]](https://github.com/mcb-dev/mCodingBot/issues/116#word-matching-rather-than-character-sequence:~:text=through%20the%20notification.-,For%20instance%2C%20the%20current%20rules%20prohibit%20hate%20speech,-%5B2%5D.)</sup>

### Note 3

https://github.com/mcb-dev/mCodingBot/blob/main/mcodingbot/plugins/highlights.py#L201. <sup>[[↑]](https://github.com/mcb-dev/mCodingBot/issues/116#word-matching-rather-than-character-sequence:~:text=a%20simple%20word%20in%20message)</sup>

**Comment by MithicSpirit** [comment]
Automatic reject because it's missing a title page. :trollface:

**Comment by qexat** [comment]
mfw the relative links are not working :skull: gg GitHub

**Comment by trag1c** [comment]
Great issue!

**Comment by MithicSpirit** [comment]
Ok more seriously I think we should do the whole tracking thing (feel free to PR). As for the extra things:
- Matching on word will come free with regex support (just add `\b`s); we don't do this yet because it's easy to do a denial of service attack through unmonitored regex (the actual implementation will have a timeout).
- Channel-dependent highlights might be nice but low priority imo.
- Adding inhibitors feels like its missing the spirit of highlights and is feature creep; imo not worth adding.
- Temporary deactivation is already possible by silencing the bot in DMs.

**Comment by zunda-arrow** [comment]
Yeah, I will merge any of these. Regex support especially.

**Comment by circuitsacul** [comment]
I agree with the initial issue of editing/deleting. Tracking highlights for a short period (maybe 30 minutes) so as to update them is a good idea.

If the original message is deleted, I think it's best to just update it to say "Original message deleted" to avoid ghost pings, like you said.

Now for the features:
 - Pattern matching: Yes, that's been "planned" for a while. Someone should do it.
 - Channel-dependent highlights: Can't think of a single usecase for this.
 - Inhibitors: Can't think of a single usecase for this either, and adds a lot (like, a ton) of complexity and changes to how highlight are handled.
 - Temporary deactivation: while you can't do this per-highlight, just... delete the highlight ig. Can't think of a real use-case for only deactivating one temporarily and not just deleting it.

**Comment by qexat** [comment]
> Matching on word will come free with regex support

Yeah, by "pattern matching" I was implying that.

All the other points are fair, I didn't expect all my suggestions to get unanimous approval anyway.

**Comment by qexat** [comment]
> Tracking highlights for a short period (maybe 30 minutes) so as to update them is a good idea.

Yeah, 30 minutes sound reasonable, even in a moderation perspective.

**Comment by qexat** [comment]
It would be cool if the bot highlighted the part that triggered also.

**Comment by MithicSpirit** [comment]
> It would be cool if the bot highlighted the part that triggered also.

I'd rather not have that since it would interfere with the message's formatting.

**Comment by qexat** [comment]
> > It would be cool if the bot highlighted the part that triggered also.
> 
> I'd rather not have that since it would interfere with the message's formatting.

I will beseech you to descry the substantive "ball" in this passage
![image](https://user-images.githubusercontent.com/43090614/222864505-93f1fb27-36e3-44da-b8f9-7c055f0b414e.png)

**Comment by MithicSpirit** [comment]
> > > It would be cool if the bot highlighted the part that triggered also.
> > 
> > I'd rather not have that since it would interfere with the message's formatting.
> 
> I will beseech you to descry the substantive "ball" in this passage
> ![image](https://user-images.githubusercontent.com/43090614/222864505-93f1fb27-36e3-44da-b8f9-7c055f0b414e.png)
>  

Third paragraph, "balled" (they probably meant "bawled").

**Comment by qexat** [comment]
> > > > It would be cool if the bot highlighted the part that triggered also.
> > > 
> > > 
> > > I'd rather not have that since it would interfere with the message's formatting.
> > 
> > 
> > I will beseech you to descry the substantive "ball" in this passage
> > ![image](https://user-images.githubusercontent.com/43090614/222864505-93f1fb27-36e3-44da-b8f9-7c055f0b414e.png)
> 
> Third paragraph, "balled" (they probably meant "bawled").

It was rather a rhetorical question ; I wanted to pointed out that it is not always obvious.

**Comment by trag1c** [comment]
Closing this since we now use https://github.com/CircuitSacul/Wires :)
