### ISSUE TITLE
Retroactively add Donor role to every user that has the Patron role

### ISSUE THREAD

**Issue by MicaelJarniac** [mcb-dev/mCodingBot#27]
Everyone with the Patron role should receive the Donor role, and the bot does somehow do that, but it seems like the bot needs to be online when the user gets the Patron role, so if the bot is offline and a user gets Patron, the user will not get Donor, like, ever.

My suggestion is for the bot to, on a programmed schedule (every day should be more than enough), look at everyone on Patron and make sure they're also on Donor.

**Comment by CircuitSacul** [comment]
Actually I don't think the bot does do that. I'm pretty sure James is doing it manually. Certainly worth adding this though.
