### ISSUE TITLE
Merge plugins and tasks

### ISSUE THREAD

**Issue by CircuitSacul** [mcb-dev/mCodingBot#37]
Tasks are just another kind of plugin. Since we already have some tasks inside the plugins folder, I think it would be best to put the `stats` "task" plugin under plugins.

cc @trag1c @Lunarmagpie

**Comment by Lunarmagpie** [comment]
I don't have a strong preference, but I do think having two folders provides some nice organization.

**Comment by trag1c** [comment]
Go for it imo
