### ISSUE TITLE
Embed reply for PEP detection

### ISSUE THREAD

**Issue by Endercheif** [mcb-dev/mCodingBot#40]
- [ ]  Add an option to allow the default link embed in the `/pep` command
- [ ] During detection for a message with pep in it, instead of sending links, send one embed listing all PEPs that were mentioned and their respective links.

> nah, but I was thinking about making the entire reply an embed so you can have hyperlinks when multiple PEPs are mentioned maybe

_Originally posted by @trag1c in https://github.com/mcb-dev/mCodingBot/pull/39#discussion_r968876667_

**Comment by CircuitSacul** [comment]
The default embed has no useful information. Might be worth trying to scrape the page to get information though.
