### ISSUE TITLE
Add search query to /pep command

### ISSUE THREAD

**Issue by CircuitSacul** [mcb-dev/mCodingBot#55]
The /pep command can have two optional arguments:
 - number
 - query

You must specify exactly one option. Number just returns that pep, whereas query will use fuzzy searching to search the peps by their titles. This is also the easiest way to introduce fuzzy searching to the codebase.

**Comment by Endercheif** [comment]
I can do this

**Comment by Endercheif** [comment]
Already experimenting with it.

**Comment by isFakeAccount** [comment]
Can somone also create a command that lets you fuzzy search mcoding videos and return link.

**Comment by trag1c** [comment]
> Can somone also create a command that lets you fuzzy search mcoding videos and return link.

Maybe read through the issues first :/ (#54)

**Comment by Endercheif** [comment]
I'm going to wait until #57 is merged before this.

**Comment by Endercheif** [comment]
nvm i'll do it now
