### ISSUE TITLE
Add the main script to pyproject.toml

### ISSUE THREAD

**Issue by qexat** [mcb-dev/mCodingBot#73]
Thoughts?

> Out of scope, but wouldn't it be simpler to add the script in the `[tools.poetry.scripts]` section of the `pyproject.toml` file?
> Then it could be run by simply doing `poetry run mcodingbot`
> In that case this could be the subject of another PR, but I'd be interested in your thoughts on this.

_Originally posted by @qexat in https://github.com/mcb-dev/mCodingBot/pull/59#discussion_r981000270_

**Comment by Lunarmagpie** [comment]
I'm 100% in support of this.
